### ISSUE TITLE
Save/dump writes values instead of definitions

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#101]
Saves are different from dumps insofar as we need to save the definitions of properties like `randomvar`, `schedule`, etc. rather than saving the value of the property.  This makes it difficult if not impossible to restore a model fully to the condition it was in at the time it was saved.

The distinction between a save and dump is not made at this point but it should be introduced. This will require a review of the code to determine where the expectation is a save versus a dump.

**Comment by aivanova5** [comment]
Closing this due to issue #588 covering this issue.
