### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#1013]
## Problem description

~~~
aivanovalocal@PC99458 Aug2021 % curl -I https://raw.githubusercontent/slacgismo/gridlabd/$(gridlabd --version=git-branch)/gldcore/version.h
ERROR [gridlabd-version] HiPAS GridLAB-D 4.2.27-210927 (develop-fix-recorder-timestep) remote not found
curl: (7) Failed to connect to raw.githubusercontent port 443: Connection refused
~~~

## Steps to reproduce

See above

## Expected behavior

No refused connection

## System information

* GridLAB-D version: `aivanovalocal@PC99458 Aug2021 % gridlabd --version=all`
~~~
HiPAS GridLAB-D 4.2.27-210927 (develop_fix_recorder_timestep) Darwin
ERROR [gridlabd-version] HiPAS GridLAB-D 4.2.27-210927 (develop-fix-recorder-timestep) remote not found
~~~
* Operating system: `Darwin PC99458 19.6.0 Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.40~1/RELEASE_X86_64 x86_64`

**Comment by dchassin** [comment]
This no longer happens as of `HiPAS GridLAB-D 4.2.29-211225 (develop) Darwin`.
