### ISSUE TITLE
Powerflow Runtime error with beauharnois-28 Docker version

### ISSUE THREAD

**Issue by yeyanzhu** [arras-energy/gridlabd-old#1037]
There are runtime errors when using gridlabd docker (beauharnois-28) for powerflow run.
No runtime errors for beauharnois-26 version when testing on same model files. 

## Steps to reproduce
1. Upgrade docker image to latest version (beauharnois-28) using 
`docker pull slacgismo/gridlabd:latest`
2. run powerflow using latest gridlabd docker image on IEEE-13 feeder model 
`docker run -it -v $PWD:/model gld  gridlabd -w /model IEEE-13.glm`
3. There are runtime errors (screenshot attached)

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

4. Repeat the same powerflow run using beauharnois-26, no errors happens.

## System information
* GridLAB-D version （docker image: beauharnois-28)
HiPAS GridLAB-D 4.2.28-211105

Error screenshot
![error](https://user-images.githubusercontent.com/22224080/144802083-13fc7b0f-eb5e-4cad-a52d-eafa10c7fe0e.png)
Testing model file (file suffix needs to change back to .glm)
[IEEE-13.txt](https://github.com/slacgismo/gridlabd/files/7658648/IEEE-13.txt)

**Comment by dchassin** [comment]
This is a problem with numpy.  You can fix this by updating numpy the usual way, e.g., “python3 -m pip install numpy —update”. Make sure you are running the local version of Python used by gridlabd.

**Comment by yeyanzhu** [comment]
Thanks for the notes. After I upgrade the Numpy version to 1.21.4 within the docker container, the run-time errors is solved.
