### ISSUE TITLE
Parallel validation can cause intermittent validation errors

### ISSUE THREAD

**Issue by catzzz** [arras-energy/gridlabd-old#1056]
## Problem description
`make install` in ./install.sh causes python installation error in latter validation. 

## Steps to reproduce
~~~
./install.sh -v -t --parallel
~~~
In later validation, the errors appear. 
`
ERROR    [INIT] : /usr/local/src/gridlabd/gldcore/autotest/test_inline_python.glm error unexpected, code 5 (simulation failed) in 0.0 seconds`
`ERROR    [INIT] : /usr/local/src/gridlabd/gldcore/autotest/test_python_property.glm error unexpected, code 5 (simulation failed) in 0.0 seconds
`
## System information

* GridLAB-D version: gridlabd --version=4.2.28-211105-master
* Operating system: Any Linux

**Comment by dchassin** [comment]
The root cause is likely that a number of validation test use the same temporary files for intermediate results and output.  This is a general problem in the autotests and needs to be address by changing how autotests that generate files name those files.
