### ISSUE TITLE
AWS EC2 set environment variable during installation process

### ISSUE THREAD

**Issue by catzzz** [arras-energy/gridlabd-old#1066]
## Problem description
`PATH=/usr/local/bin:$PATH` cannot be set permanently by running ./install.sh. Without `PATH` variable during installation, users still can complete the installation correctly. However, `gridlabd` command cannot be performed directly under `gridlabd` folder after installation. Users have to find it in the build folder.

## Expected behavior
None
## System information
* GridLAB-D version:
* Operating system: AWS ec2

## Supporting information
none

**Comment by dchassin** [comment]
This can be done by modifying the shells' `.rc` files.

**Comment by dchassin** [comment]
@catzzz, can we close this or is this still something we need to fix?

**Comment by catzzz** [comment]
Yes. this issue had been fixed.

**Comment by catzzz** [comment]
Close issue
