### ISSUE TITLE
AWS endpoints no longer work

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#1078]
## Problem description

A number of important AWS endpoints return errors. Please verify that *all* endpoints in `gridlabd/S3` work correctly and fix S3/Route 53/CloudFront as needed.

## Steps to reproduce

Try the following commands:

1. `git clone https://source.gridlabd.us/`
2. `curl https://code.gridlabd.us/master/README.md`.

## Expected behavior

1. should clone the source code into `gridlabd` folder.
2. should download the master README file.

**Comment by catzzz** [comment]
2. Fixed `curl https://code.gridlabd.us/master/README.md.`  error by changing the redirect URL `github.com/slacgismo/gridlabd/raw/` in S3 to `raw.githubusercontent.com/slacgismo/gridlabd/`.
  - The curl command should change as `curl -L https://code.gridlabd.us/master/README.md.`. The `-L` option enables `curl` to follow the redirection.

**Comment by catzzz** [comment]
1. Fixed by resetting the AWS Cloudfront endpoint.
