### ISSUE TITLE
Missing default timezone setup in the installation process under Windows WSL/Debian.

### ISSUE THREAD

**Issue by catzzz** [arras-energy/gridlabd-old#1087]
## Problem description

Missing default timezone setup in the installation process under Wondows 10 WSL/Debian:11

## Steps to reproduce
Under Windows 10  WSL/Debian:11 
~~~
cat /etc/timezone
~~~
the output is 
~~~
Etc/GMT+8.
~~~ 
Error output
~~~
make[3]: Leaving directory '/usr/local/src/gridlabd'
make[2]: Leaving directory '/usr/local/src/gridlabd'
make[1]: Leaving directory '/usr/local/src/gridlabd'
Setting /usr/local/opt/gridlabd/4.2.30-220119-develop_fix_debian11_setup to the current system version
ERROR    [INIT] : tz_info: '-088' not a timezone-format string
ERROR    [INIT] : timezone '-088' was not understood by tz_name.
ERROR    [INIT] : locale pop failed; stack empty
~~~
 

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.2.30-220119
* Operating system: 
4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 GNU/Linux

**Comment by dchassin** [comment]
We do not have a current PR for Debian 11.  Do we need on yet?

**Comment by catzzz** [comment]
set Local timezone from web 
`ln -snf /usr/share/zoneinfo/$(curl https://ipapi.co/timezone) /etc/localtime`
