### ISSUE TITLE
Random number entropy degeneracy warning needs to be removed

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#110]
The warning that the entropy of the random number seed is lost is unnecessary and should be removed.

**Comment by aivanova5** [comment]
Are you referring to this warning "randunit() introducing extra randomness to prevent state stagnation and infinite loops" in random.c

**Comment by dchassin** [comment]
Yes. In several branches I have simply removed the warning.

**Comment by aivanova5** [comment]
output_warning was changed to output_verbose in a commit on Dec 28th - closing issue.
