### ISSUE TITLE
Not all files present after manually setting template configuration. 

### ISSUE THREAD

**Issue by campout12** [arras-energy/gridlabd-old#1108]
## Problem description

After setting the template configuration to my personal repo, the file "default_billing.py" cannot be found. The share folder only seems to have files labeled with "tariff."

## Steps to reproduce

1. Run these commands in docker image slacgismo/latest 
`gridlabd template config set GITUSER johnsonhsiung`
`gridlabd template config set GITREPO openfido-tariff-design`
`gridlabd template config set GITBRANCH develop-tariff-design-openfido`
`gridlabd template config set DATADIR /model/us/ca/slac`
`gridlabd template get tariff_design`

2. Run `gridlabd model.glm -t tariff_design` with an appropriate model.glm (can be found here https://github.com/slacgismo/gridlabd-template/tree/add-tariff-design/US/CA/SLAC/tariff_design) 

3. See error about missing default_billing.

## Expected behavior

Tariff design template runs smoothly. 

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.2.29-220103 (master) Linux
* Operating system: Linux ee69df51fd76 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dchassin** [comment]
Did you add the file to the `.catalog` file?
