### ISSUE TITLE
Exception raised by vegetation geodata query

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#1140]
## Problem description

The `gridlabd geodata` command reports an error when merge the `vegetation` dataset with a 2021 CPUC fire incident report from SCE.

~~~
ERROR [geodata/vegetation]: index 1080 is out of bounds for axis 0 with size 1080
~~~

## Steps to reproduce

Download the following CSV data:

[CA_SCE_2021.csv](https://github.com/slacgismo/gridlabd/files/8453748/CA_SCE_2021.csv)

Run the following command:

~~~
shell$ gridlabd geodata merge -D vegetation CA_SCE_2021.csv 
~~~

## Expected behavior

The geodata command should append the vegetation height, coverage, and base to the columns.

## System information

* GridLAB-D version: `HiPAS GridLAB-D 4.2.31-220325 (develop) Darwin`
* Operating system: `Darwin PC98798 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

## Supporting information

None

## Attachments

* [CA_SCE_2021.csv](https://github.com/slacgismo/gridlabd/files/8453748/CA_SCE_2021.csv)

**Comment by xiefuhong** [comment]
The index bug is fixed and here is the example output
[test_CA_SCE_2021.csv](https://github.com/slacgismo/gridlabd/files/8456276/test_CA_SCE_2021.csv)
