### ISSUE TITLE
Add flag to indicate Critical Facility (PSPS)

### ISSUE THREAD

**Issue by ktehranchi** [arras-energy/gridlabd-old#1161]
## Background
We are interested to have a weighting for critical facilities in the PSPS use case. We are interested in tracking the loads that are "critical" to give them higher weighting in the PSPS optimization.

## Proposed solution
The proposed solution is to add a flag field "CriticalFacility" to the meter (or house) object in the GLM model.

## Alternatives
Without this flag, I can manually set flags in my model and will do so if this is not implemented.

**Comment by dchassin** [comment]
Propose the following change to `meter` object only (not `triplex_meter`).

~~~
class
{
  bool is_critical; // flag to indicate facility provide critical/emergency services (default FALSE)
}
~~~
