### ISSUE TITLE
Potential CYME 9 Rev 6 MDB to GLM conversion issue

### ISSUE THREAD

**Issue by MitchellAV** [arras-energy/gridlabd-old#1284]
## Problem description

When using the GridLAB-D CYME MDB to GLM converter, certain MDB files that are in the latest version of CYME (CYME 9.0 Rev 6) is unable to successfully convert into a working GLM file. This error seems to be inconsistent as several CYME 9 Rev 6 files were tested of different sizes and the issue was not present. Need to test further with other CYME MDB files that are from the latest version of CYME to be able to confirm that the current converter is working correctly or not.

## Steps to reproduce

1. Converting an MDB file to GLM using the GridLAB-D cli
e.g. `gridlabd -D mdb_load_options="-t cyme" <mdb_filename>.mdb`

## Expected behavior

Should be able to supply an MDB file to the GridLAB-D command line and be able to use the MDB to GLM converter with the CYME flag to converter the CYME file to GLM.

## System information

* GridLAB-D version: (Insert output of `gridlabd --version=all` here)
* Operating system: (Insert output of `uname -a` here)

## Supporting information

No further supporting information available at this time.

## Attachments

(If applicable, attach screenshots, supporting files, and other data need to help explain and reproduce the problem. If you encountered a program fault or internal error, and you have built GridLAB-D with `-O0 -g`, then on Linux systems you can attach the output of the following command:)
~~~
bash$ ulimit -c unlimited
bash$ gridlabd <your command options...>
... crash dumps core ...
bash$ gdb -batch -ex "backtrace" $(gridlabd --version=install) ./core
~~~

(If you are running on macOS, you must use `lldb` to do the following.)
~~~
bash$ ulimit -c unlimited
bash$ ls -lt /cores # find the most recent core dump
bash$ lldb -c /cores/core.<number>
(lldb) bt -- backtrace
~~~

**Comment by dchassin** [comment]
@MitchellAV, is this still an open issue?

**Comment by MitchellAV** [comment]
@dchassin Yes, this is still an open issue. Once we obtain the files I requested from SCE, we should be able to move forward with determining if this issue is valid or not.
