### ISSUE TITLE
./build.sh --install --validate results in incorrect linking

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#1285]
## Problem description

When using `./build.sh --install --validate` a number of files generate error below: 

`"libc++abi: terminating with uncaught exception of type char*"`

## Steps to reproduce

As above

## Expected behavior

No validation errors

## System information

* GridLAB-D version: 4.3.1-230510-develop_fix_install-darwin_21-x86_64
* Operating system: Darwin PC95555 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

**Comment by dchassin** [comment]
@aivanova5, is this still an open issue?

**Comment by dchassin** [comment]
Unable to reproduce anymore.
