### ISSUE TITLE
create_poles subcommand adds poles along switches

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#1320]
## Problem description

When using `create_poles` subcommand to generate a set of poles along lines, the algorithm also creates poles along switches as well. underground lines are ignored, as expected.

## Steps to reproduce

Trying this with 123.glm

`#python -m create_poles 123.glm --spacing=100 --pole_type=WOOD-EC-45/4 --weather=example --ignore_location --output=IEEE123_poles.glm`

## Expected behavior

No poles along switches

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.3.3-230727 (develop_add_group_tool) Darwin
* Operating system: Darwin PC99458 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

[test.zip](https://github.com/arras-energy/gridlabd/files/12188762/test.zip)

**Comment by dchassin** [comment]
Aren't switches always mounted on poles?
