### ISSUE TITLE
Support Creation Fault on a Specific Object at a Specific Time or Time Step

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#143]
It should be possible to create a fault at a specific location at a specific time or time step.

**Comment by dchassin** [comment]
A deterministic `eventgen` object can be specified as

object eventgen {
	name DeterEvent;
	parent MetricsObj;
	fault_type "DLG-X";
	manual_outages "line12,2000-01-01 5:00:00,2000-01-02 6:00:00";
	}
See http://gridlab-d.shoutwiki.com/wiki/Reliability_User_Guide for details.
