### ISSUE TITLE
Create Package Package to Support Python Utilities

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#144]
Python utilities for GridLAB-D should be available to be used by client software.  At the very least this package should be usable by software that is bypassing the REST API, although it may be useful when using REST as well.

The Python code that was written for GRIP to concatenate the multiple multi-recorder CSV files should be moved into this new package.

**Comment by dchassin** [comment]
A deterministic `eventgen` object can be specified as
~~~
object eventgen {
	name DeterEvent;
	parent MetricsObj;
	fault_type "DLG-X";
	manual_outages "line12,2000-01-01 5:00:00,2000-01-02 6:00:00";
	}
~~~
See http://gridlab-d.shoutwiki.com/wiki/Reliability_User_Guide for details.
