### ISSUE TITLE
Version info is not correct when branch is ahead of remote

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#152]
Some cases do not seem to be handled correctly by `utilities/build_number`.  The code needs a review and possible rewrite so it handles all the known cases.

1. If HEAD is tagged, then display `URL/tree/tagname`. 
2. If HEAD is same as remote, then display `URL/tree/branchname`.
2. If HEAD is behind remote, then display remote `URL/commit/commit_id`
3. If HEAD is ahead of remote then display `user@host:path:commit_id`

**Comment by jongoncalves** [comment]
@dchassin I can probably pick up something like this if you don't mind. Seems pretty straightforward.

**Comment by dchassin** [comment]
The script is kind of messed up because it's evolved from the old sourceforge/svn code. It might be good to rewrite it after clarifying exactly all it's supposed to do.

**Comment by dchassin** [comment]
I think we need to clean up version so it's more consistent and predictable.  Here's a suggestion.

1. make version always show the same thing, e.g., the name, version and build, but nothing else, i.e.,
~~~
host% gridlabd --version
GridLAB-D 4.2.0-190425
~~~

2. add a new command that gives more information about the build, e.g.,
~~~
host% gridlabd --build-info
application: GridLAB-D
version: $major.$minor.$patch
build: $(date '+%y%m%d')
source: $(git remote | head -n 1)
source_url: $(git remote get-url $remote)
branch: $(git branch | grep '^*' | cut -f2 -d' ')
id: $(git log -n 1 | sed -n '1s/^commit //p')
system: $(uname -sr)
release: $(./requirements info --release)
options: $(./customize configure status)
status: $(git status -b --porcelain)
~~~
We should also include a global variable to affect the format of the output, e.g., `version_format=raw`, as shown above, or `version_format=json` for a JSON entity, or `version_format=xml` for an XML entity.

The entry for `release` should obtain the `requirements` used to setup the system, e.g., 'Darwin', 'Centos-Linux`. This may require a change to the requirements script to allow this option to work.

The entry for `options` should obtain the status from the `./customize configure status` script.
