### ISSUE TITLE
Slow computing times running on Docker

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#169]
Running GridLAB-D validation gives inconsistent timing results on docker. 

When docker has been restarted validation time with `-T 3`: ~ 204s 
After multiple runs (inconsistent as to what event reduces the time) in the same image the time increases with `-T 3`: ~1000s 
No timing issues found through the host system or VMware Centos7

Every odd time validation is executed, segmentation error occurs right away: 
~~~
/usr/local/bin/gridlabd: line 360: 98768 Segmentation fault      "$bindir/gridlabd.bin" "$@"
~~~
And executing validation command again - allows to validate at ~200s time.

**Comment by aivanova5** [comment]
Attempts to reproduce the slow down of validation on docker (failed attempts): 
1. Running make install again between validations 
2. Killing the validation process and following by validation 
3. Exiting the image and starting a new one

**Comment by aivanova5** [comment]
Found the problem occurring when the computer goes to sleep and then used again after wake-up. Work-around is through re-starting the docker for now.

**Comment by dchassin** [comment]
Good discussion on this topic: https://hackernoon.com/another-reason-why-your-docker-containers-may-be-slow-d37207dec27f

**Comment by dchassin** [comment]
Some evidence has emerged recently that now centos:7 is slow all the time.

**Comment by dchassin** [comment]
Suggestion on this: modify `exec_clock()` so it does not call `ftime()` when the profiler is off, and modify all the autotests so they don't use the profiler. Remember to add a caveat to the global profiler docs to note that performance may be affected by use of the profiler.
