### ISSUE TITLE
Objects need to be able to request checkpoints

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#177]
Objects should be able to set a flag that we need a checkpoint now (global flag).  When synchronization is done, it should force an immediate checkpoint.

Can these checkpoints be based on periodic time step intervals or conditions reached by the objects (e.g., the state of an object changes and force a checkpoint)

**Comment by dchassin** [comment]
The checkpoint system is largely deprecated now. Closing.
