### ISSUE TITLE
Add support to export asset names/global variables in CSV file

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#19]
Add command line argument or GridLAB-D configuration that allows the asset names and global variables to be exported

**Comment by dchassin** [comment]
@jcald1, please confirm that we mean to allow globals and header properties to be recorded to CSV rather than exported to JSON (which is already supported).

**Comment by dchassin** [comment]
PR #70 is ready for review. It adds the ability to refer to globals in recorders.

**Comment by jcald1** [comment]
Closing as this has been implemented in PR #70.
