### ISSUE TITLE
Add support to export greater than 1024 column characters to CSV file from multirecorder

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#20]
The multirecorder limits the column to 1024 characters.  Add support to export more than 1024 characters.

**Comment by dchassin** [comment]
This will be addressed initially by a work-around using multiline properties (see PR #62). 

When work on https://github.com/dchassin/gridlabd/tree/dchassin/string_property is completed, this will be address in a single-line property by the variable length string property type.

**Comment by jcald1** [comment]
@dchassin, does each property row's output have to stay within 1024 columns or there is no limit any longer to the CSV column length?

**Comment by dchassin** [comment]
PR #62 merged.  Closing.
