### ISSUE TITLE
Add support for ISO 8601 Datetime formats

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#21]
GridLAB-D should be able to handle datetime formats such as:

```
2008-09-15T15:53:00+05:00
2018-10-23T17:15:35:00Z
```

**Comment by dchassin** [comment]
@jcald1: The full standard is rather complex.  Do we want to implement all of it, or just a subset of the standard? If only a subset, could we identify which parts?  See https://en.wikipedia.org/wiki/ISO_8601 for details.

**Comment by dchassin** [comment]
Some issues that need to be addressed:

1) GridLAB-D requires 1 nanosecond resolution timestamps when running in delta mode.  ISO8601 seems to only support a maximum resolution of 1 millisecond.  So this format is not technically compatible with GridLAB-D's technical requirements for dynamic simulation.

2) To completely support this format we need to support repeating, truncated and interval values, such as are used in schedules, climate and players, respectively.  This is definitely not a simple task and potential a weeks long effort to complete and validate.

**Comment by jcald1** [comment]
We really don't need to support all formats described in this
standard.  What we really need is to support the BigQuery canonical
timestamp format:

YYYY-[M]M-[D]D[( |T)[H]H:[M]M:[S]S[.DDDDDD]][time zone]

as described in:
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types

This format supports up to microsecond precision.  For delta mode,
could we just go ahead and add more digits even though technically it
does not meet the canonical standard for BigQuery?  If it becomes a
problem for a tool parsing the data, the user could just switch to the
current format that is supported, or convert to a more precise format.
Some tools may be more permissive than the standard(s).

For non-delta mode, we could just stick to the canonical model.

**Comment by jcald1** [comment]
@dchassin , in addition to the canonical format above, it would be good to support the UTC offset format described in the link above right below the description of the canonical format.  These two formats themselves have several variations based on precision (precision to the second vs to the millisecond, etc.) and if it's too much work to fully support each of these variations, we could just pick ones that make the most sense.  e.g., precision to the second for non-delta mode with and without the offset (.01Z and .01-08:00), along with the ones for delta mode.

**Comment by dchassin** [comment]
This is address by PR #68.

**Comment by jcald1** [comment]
@dchassin , I tried the following formats and they didn't work:

```
2008-09-15T15:53:00+05:00
2018-10-23T17:15:35:00Z

ieee123_pole_vulnerability.glm(76): load failed at or near 'clock {...'
FATAL    [INIT] : shutdown after command line rejected
```
