### ISSUE TITLE
Exercise validation files should be moved to their own folder

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#213]
There are scattered exercise files all over the repository which should be moved into their own folder and amended to include assert modules.

**Comment by dchassin** [comment]
This should be dealt with as part of the restructuring of the installation. See PR #374.

**Comment by aivanova5** [comment]
Do we want these files to still get relocated after the new structure is in place?

**Comment by dchassin** [comment]
This has been largely done by creating the tutorials.
