### ISSUE TITLE
Powers in house_e.cpp are inconsistent

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#215]
One example is evident when `hvac_load` is higher than `total_load`. Upon investigation `total_load` is actually a magnitude of complex power where `hvac_load` is only the real power of the hvac demand. 

Further investigation is required to confirm the consistency of the units.

**Comment by dchassin** [comment]
@aivanova5, it's not clear whether this issue was fixed by #217.

**Comment by dchassin** [comment]
@ftuffner, any thoughts on this issue? Is this what is intended?

**Comment by dchassin** [comment]
This is unlikely to result in any changes to the definitions of the properties, at least not in the near term. Closing.
