### ISSUE TITLE
Implement fault in pole model when critical stress is reached.

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#23]
When the critical stress is reached, it should trigger a fault.

Whether or not a fault should be triggered when the critical stress is reached should be a parameter in the pole object.  The default should probably be true.

Note: Depending on what is decided on how to handle wind susceptibility, we may want the configuration property to allow the modeler to trigger a fault based on the wind speed at failure property (calculated from wind susceptibility).  The fault could be caused by either the pole stress or wind speed at failure threshold reached (whichever comes first), only or the other threshold reached, or only when both thresholds are reached.

**Comment by jcald1** [comment]
@dchassin , I added some more details to the issue.

**Comment by dchassin** [comment]
Faults should be triggered only when the reliability is loaded. Otherwise the power flow module will not work. We need to integrate the pole failure model with the reliability module for this to work properly.

**Comment by dchassin** [comment]
This is being address by PR #63.
