### ISSUE TITLE
object-specific precommit function in python version not working

### ISSUE THREAD

**Issue by mlamlamla** [arras-energy/gridlabd-old#232]
I am trying to write an object specific precommit function in the python version of GridlabD but it returns an error for different possible return values (t, t_next, True).

To reproduce, run "main_testX.py" in the zip folder below.

@dchassin @aivanova5

**Comment by aivanova5** [comment]
Simplified model that fails is here 
[precommit_bug.zip](https://github.com/dchassin/gridlabd/files/3298945/precommit_bug.zip)

**Comment by aivanova5** [comment]
Current implementation of precommit does not return a timestamp and returns a binary (where False is continue). This should be fixed for correct operation.

**Comment by dchassin** [comment]
I'm going to post a pseudo-fix that allows you to return a timestamp, but doesn't use the timestamp to set the next clock.  We'll figure out how to do that later.  Right now, advise using `gridlabd.NEVER` for continue the simulation, and `gridlabd.INVALID` to stop it.

**Comment by mlamlamla** [comment]
This fix works well but we need a consistent fix.

**Comment by dchassin** [comment]
Recommend we implement all event handlers to use the same protocol, e.g., called with one timestamp, and return one timestamp.
