### ISSUE TITLE
tzinfo.txt has "suspicious" timezone specifications

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#241]
tzinfo.txt should be revised and updated with new timezone standards. Some definitions are probably questionable, two obvious examples: 
(1) GMT0GMT has the same name for winter and summer time.  Should it be GMT0GDT?
(2) EST-10 (Australia) which is defined with the same name as EST-5 (US East coast). This definition is obsolete and should be deleted.

**Comment by dchassin** [comment]
(1) `GMT0GMT` has been changed to `GMT0BST`.
(2) `EST-10` is correct for AU. The correct US timezone is `EST+5`.
