### ISSUE TITLE
Validation failure doesn't trigger a failure in CircleCI

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#267]
CircleCI doesn't pick up validation errors. See attached
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/28273120/62148294-4731a400-b2ae-11e9-9ce3-c236870938aa.png">

**Comment by jongoncalves** [comment]
I think this should change to -> GLD validation step doesn't properly handle/raise python exceptions. From to the screenshot the validation succeeded according to its report.

**Comment by dchassin** [comment]
I think the output is misleading.  Can we identify the file that is causing this?

**Comment by dchassin** [comment]
@aivanova5, I'm not clear whether this is a bug or question.  Do we need to do something?
