### ISSUE TITLE
Tape module seg fault on 1024 limit and json dump problems

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#273]
New issue checklist (please delete this list when creating the issue):
1. Unable to define long property lists on recorders 
2. Incorrect json dump of recorders
[test_multi_recorder_multiple_properties.glm.zip](https://github.com/dchassin/gridlabd/files/3458738/test_multi_recorder_multiple_properties.glm.zip)

**Comment by dchassin** [comment]
@aivanova5, please verify this has been resolved and disposition accordingly.

**Comment by dchassin** [comment]
@aivanova5, can we close this now?
