### ISSUE TITLE
ISO timestamp can't be read as a macro 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#282]
The ISO8601 timestamp gets stripped off of the quotes when defined as a global. Temporary fix has been issued. The string has to be defined in quotes and the reference must also be in quotes. Example: 
#define TIMEZONE=EST+5EDT
#define STARTTIME = "2019-01-01T00:00:00-05:00"
#define STOPTIME="2019-01-30T00:01:00-05:00"
clock {
	timezone ${TIMEZONE};
	starttime "${STARTTIME}";
	stoptime "${STOPTIME}";
}
[Archive.zip](https://github.com/dchassin/gridlabd/files/3493696/Archive.zip)

**Comment by aivanova5** [comment]
When defining a timestamp as ISO8601 the simulation doesn't start at the defined time... The attached file has start and stop time in 2018 however the simulation starts in 2010....

[Archive.zip](https://github.com/dchassin/gridlabd/files/3522079/Archive.zip)

**Comment by dchassin** [comment]
Recommend the following change:
~~~
@@ -1188,8 +1188,8 @@ TIMESTAMP convert_to_timestamp(const char *value)
		S = (unsigned short)s;
		unsigned int ns = (s-S)*1e9;
		DATETIME dt = {Y,m,d,H,M,S,ns,0};
-		TIMESTAMP t = mkdatetime(&dt);
-		return t - (tzh*60+tzm)*60;
+		dt.tzoffset = (tzh*60+tzm)*60;
+		return mkdatetime(&dt);
	}

	/* scan ISO format date/time */
~~~
