### ISSUE TITLE
Support the Continuation of a Simulation Run Using the State of a Last Simulation Run

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#30]
After running a simulation using the -o flag with an XML or JSON output file name, the user should be able to feed that final state file into a new simulation run so that the final state after the second run is the same as if a single simulation had been run with the exact same duration/number of time steps.

The final random state of an object after the first run should be carried over as the starting random state of the same object in the next simulation run, along with the other states. The original random seed should be carried forward as well, but any new random numbers would continue from the current random state, not the original random seed.  At the end of the simulation the random state and random seed would match the values as if there had been a single run.

**Comment by aivanova5** [comment]
This is now supported but with issues as listed in #588
