### ISSUE TITLE
Timestamp pushes through erroneous input string 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#300]
When given a string for stop time for example as...`"2020-02:28 00:00:00 PST"` *Notice the semicolon between the month and day which is an invalid definition... the model does not throw an error and returns `NEVER` instead.

**Comment by dchassin** [comment]
@aivanova5, please verify this is still a problem and disposition accordingly.

**Comment by aivanova5** [comment]
Still active...
~~~
PC95555:test_pole alyona_slac$ gridlabd test_pole.glm
test_pole.glm(8): expected time value
FATAL    [INIT] : shutdown after command line rejected
~~~
