### ISSUE TITLE
Master fails to pass test_pole_NR.glm through validate.py

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#379]
Problem with validation through `validate.py`. The error is as follows: 
~~~
host% python3 gldcore/link/python/validate.py
...
Running test_pole_NR.glm...
sh: line 1:  3139 Segmentation fault: 11  /usr/local/bin/python3 /Users/alyona_slac/gridlabd/macosx/gldcore/link/python/python_gridlabd.py -W /Users/alyona_slac/gridlabd/macosx/powerflow/autotest/test_pole_NR test_pole_NR.glm > gridlabd.out 2>&1
FAIL /Users/alyona_slac/gridlabd/macosx/powerflow/autotest/test_pole_NR/test_pole_NR.glm exit 139
~~~

**Comment by aivanova5** [comment]
We're not validating through python any more, I vote we close this @dchassin

**Comment by dchassin** [comment]
Good point. But maybe we should be validating the python libraries.  Right now, there are no tests to ensure that they're coded and built correctly.

**Comment by dchassin** [comment]
I just ran the python validation and the result is unsatisfactory:
~~~
Tested.... 707
Failed.... 56
Passed.... 651 (92.1%)
Time...... 338.4 sec
~~~

**Comment by aivanova5** [comment]
Ouch, can we use validate.py to track down the `test_pole_NR.glm` intermittent problem since it seems to fail every time through python validation routine?
