### ISSUE TITLE
CEUS unable to dump to JSON 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#382]
Running `gridlabd test_ceus.glm -o test.json` results in 

~~~
/usr/local/bin/gridlabd: line 368: 79850 Segmentation fault: 11  "$bindir/gridlabd.bin" "$@"
~~~

Using test file in: `source/commercial/autotest/test_ceus.glm`

**Comment by dchassin** [comment]
This should be addressed by PR #389
