### ISSUE TITLE
simulation hangs on modified IEEE-13 bus model

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#383]
Simulation locks up tight when running the attached simulation.
[IEEE-13.glm.gz](https://github.com/dchassin/gridlabd/files/3725818/IEEE-13.glm.gz)

**Comment by dchassin** [comment]
Having a "*" in the filter definition makes it lock up.

**Comment by aivanova5** [comment]
Can't download the attached any longer...

**Comment by dchassin** [comment]
@aivanova5, is this issue still open?
