### ISSUE TITLE
ISO8601 output capability 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#384]
Currently the code can handle input timestamp in the format: 
`2020-01-30T00:00:00-05:00` 
However, the output capability is non-existent and would be nice to have.

**Comment by jcald1** [comment]
@dchassin , ideally we would support ISO8601 formats in both the CSV output and the gridlabd.err file in GRIP.

**Comment by dchassin** [comment]
@jcald1, in theory changing the core datetime formatting routine should address all of these. But do check them all just in case something doesn’t use the core code.
