### ISSUE TITLE
Anaconda python path conflict

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#455]
# Problem description
When setting up a new gridlabd install on a Mac, while anaconda exists on the system the paths are confused and are not set correctly.

# Steps to reproduce
Explain how to reproduce the behavior
Go through install process on a new clone of the repo

# Expected behavior
No error while installing

# System information
* GridLAB-D version: develop branch from 12/6/19
* Operating system: DARWIN

# Supporting information
N/A

# Attachments
N/A

**Comment by dchassin** [comment]
Recommend always using `gridlabd my-script.py` instead of `python3 my-script.py`.
