### ISSUE TITLE
Make clean gets rid of configuration

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#456]
# Problem description
When issuing `make clean` `autoreconf -isf; ./customize configure` must be re-run ie files that shouldn't be deleted are getting deleted through the command.

# Steps to reproduce
Explain how to reproduce the behavior
Run `make clean`

# Expected behavior
Should be able to run `make install` after `make clean`

# System information
* GridLAB-D version: develop branch 12/6/19
* Operating system: DARWIN

# Supporting information
N/A

# Attachments
N/A

**Comment by dchassin** [comment]
This no longer seems to occur. However, the `make install` produces a lot of `file exists` error messages after `make clean` is run.  

@aivanova5, can you confirm that this is no longer a problem and close if ok.
