### ISSUE TITLE
Docker platform doesn't build with the necessary gdb libraries 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#49]
When checking out a docker image the permissions for debugger are not enabled. In addition, the image doesn't build right away with the correct libraries: 

To get around it and to manually enable gdb I had to do two steps:

(1) correctly allow permissions as: 

docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -it -v $(pwd)/gridlabd:gridlabd image_name

then run within docker bash, 

(2) %host: debuginfo-install glibc-2.17-222.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64

**Comment by dchassin** [comment]
This will be addressed by issue #88.
