### ISSUE TITLE
Output streams are not directly correctly

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#507]
## Problem description
When running validation on gldcore tests such as `test_inline_python.glm` generate console output. Other files with similar behavior: `test_subcommand_help.glm` and `test_subcommand_aws.glm`

## Steps to reproduce
(Explain how to reproduce the behavior, e.g.,)
Run `test_inline_python.glm `

## Expected behavior
No output to console

## System information
* GridLAB-D version: `HiPAS GridLAB-D 4.2.1-200107 (develop_fix_websites) Darwin`
* Operating system: Darwin vpn-clients-gw2-113-188.slac.stanford.edu 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

## Attachments
(If applicable, attach screenshots, supporting files, and other data need to help explain and reproduce the problem.)

**Comment by dchassin** [comment]
Done. See PR #549
