### ISSUE TITLE
Publish additional pole properties

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#52]
Publish the following additional pole properties:

total_moment
resisting_moment
wind speed at failure
the components of the calculation for wind speed at failure

**Comment by dchassin** [comment]
@aivanova5: see PR #54 for action items.

**Comment by jcald1** [comment]
Implemented in https://github.com/dchassin/gridlabd/pull/54

**Comment by aivanova5** [comment]
@dchassin, can you check over the math on this issue

**Comment by dchassin** [comment]
Looks ok. If problems emerge, we can open a new issue. Closing.
