### ISSUE TITLE
line_sensor properties throw an error in json2glm converted glm file (IEEE123 feeder model)

### ISSUE THREAD

**Issue by yeyanzhu** [arras-energy/gridlabd-old#529]
## Problem description
Can not run json2glm converted glm file due to inability to initialize the line_sensor object
## Steps to reproduce
Take IEEE123 feeder model as the testing case, which contains the line sensor objects
1. using gridLAB-D to output json file from original feeder model file
2. using json2glm to convert json file to glm file
3. run power flow using the converted glm file
4. Initialization error will show, related to line-senor property "co-variance"

## Expected behavior
No error when running converted glm file

## System information
* GridLAB-D version: 
GridLAB-D 4.2.0-191209 (master) LINUX

## Supporting information
Error screenshot attached 
![image](https://user-images.githubusercontent.com/22224080/73513661-47b50f80-43a3-11ea-9f33-0dcd9aeedebe.png)

## Attachments
json file, converted glm file attached

[IEEE123Issue.zip](https://github.com/slacgismo/gridlabd/files/4137674/IEEE123Issue.zip)

**Comment by dchassin** [comment]
Tested this JSON file with `develop` and found additional problems:
1. The timezone is not converted properly.
2. The conversion of `kmlhost` fails.

**Comment by dchassin** [comment]
@yeyanzhu, could you post the original GLM file that generated the JSON file?

**Comment by yeyanzhu** [comment]
I re-run the testing. The original GLM file/json file/converted glm file are all attached. 
I already manually removed the KMLhost part from the converted glm file.

[IEEE123_Testing.zip](https://github.com/slacgismo/gridlabd/files/4143429/IEEE123_Testing.zip)

**Comment by aivanova5** [comment]
@yeyanzhu What are you trying to achieve by using line sensors? Line sensors were developed as a custom module for a specific project. In addition, line sensors are not widely used in the industry so there may be a better way to address what you're trying to do that avoids this problem.

**Comment by Hitachi-ESL** [comment]
Hi Alyona, I am not using line sensors for any particular case study.  I just happened to use this model file for a general file conversation consistency testing.

**Comment by aivanova5** [comment]
@yeyanzhu is this still an issue?

**Comment by Hitachi-ESL** [comment]
Hello Alyona,

The bug is not an issue for me. Thanks for checking

Yanzhu
