### ISSUE TITLE
Ability to record meter properties directly on node and poles

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#56]
We would like to be able to record the meter properties directly on a pole (e.g., measured_real_power).  This would allow us to record various properties under a single object (e.g., pole stress and measured real power on the same pole object).

**Comment by dchassin** [comment]
We can use a recorder to measure pole stress and other properties of poles.

We cannot practically measure total power on a node objects. It is only practical to measure the power flowing through a link into a node.  We can use the power in/out properties of the links to do that.
