### ISSUE TITLE
json2csv converter 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#568]
Voltage v.s. Distance data
- Output the voltage v.s. distance data for further post-processing

This can be done similarly to existing json2png-profile.py, suggest using “json2csv.py” convert using a new type, e.g., “json2csv-profile.py”

**Comment by yeyanzhu** [comment]
Is the "json2png-profile.py" in any sub-folder of the GridLAB-D source code I can download?

**Comment by dchassin** [comment]
> Is the "json2png-profile.py" in any sub-folder of the GridLAB-D source code I can download?

I've just opened PR #617 for this.  It is a work in progress and is not available on any other branch yet.
