### ISSUE TITLE
#on_exit command fails to process -1 exit status correctly

### ISSUE THREAD

**Issue by yeyanzhu** [arras-energy/gridlabd-old#611]
## Problem description

When `#on_exit -1` is used to catch all non-zero exit codes, the command given is not executed.

## Steps to reproduce

1. Add the following commands to dump the error code to files for status checking.
~~~
#on_exit 0 python3 ExitCheck.py ${exit_code}
#on_exit -1 python3 ExitCheck.py ${exit_code}
~~~
The python code (ExitCheck.py) is to output exit_code to some file.

2. Use `gridlabd -C main.glm` command to run model compilation 

3. Here are some testings and results I got:

  - When the model complication succeed, the command `#on_exit 0` will be triggered and exit-code is recorded as zero in the status recording file. However, when exit code is non-zero, the `#on_exit -1` command fails to work correctly, nothing is recorded. Here, the weather file (`CA-Bakersfield_Meadows_Field.tmy3`) is removed to create model compilation error. 

  - Then I change the second command to `#on_exit 5 python3 ExitCheck.py ${exit_code}`, since in json file the exit code is recorded as 5. Then, the command of `#on_exit 5` will be triggered to output exit_code to the status recording file. However, in the status recording file, the exit_code is recorded as zero instead of non-zero value, e.g. 5.

## Expected behavior

Use the command  `#on_exit -1 python3 ExitCheck.py ${exit_code}` to catch model failure status correctly.

## System information

* GridLAB-D version: 
HiPAS GridLAB-D 4.2.1-200223

## Supporting information

None

## Attachments

The attachment include the IEEE123 feeder model file, python file, and status file.
[OnExit_Testingfile.zip](https://github.com/slacgismo/gridlabd/files/4464224/OnExit_Testingfile.zip)

**Comment by dchassin** [comment]
Per @KellyYe this issue is reopened because the docker image autotest fails to detect the failure of `gldcore/autotest/test_on_exit_1.glm`.  This failure can be detected manually by changing the `#on_exit -1 exit 0` command to `#on_exit -1 echo "the error has been caught"`.  If this message appears, then the test worked properly. If this message does not appear, then the test did not work properly.  If the test succeeds without the message appearing, then the bug is present.

**Comment by dchassin** [comment]
The problem does not occur when optimization is turned off.
