### ISSUE TITLE
csv to glm converter does not handle different codecs

### ISSUE THREAD

**Issue by saraborc** [arras-energy/gridlabd-old#670]
## Problem description
When you save the csv file using a non-standard codec, csv to glm fails. No way to specify codec when calling csv to glm.

## Steps to reproduce
1. Save csv using a non-standard codec
2. Use `#input myfile.csv -t config -f config`
~~~
Traceback (most recent call last):
  File "/usr/local/opt/gridlabd/4.2.1-200522-master/share/gridlabd/csv2glm.py", line 69, in <module>
    mod.convert(input_file,output_file,options)
  File "/usr/local/opt/gridlabd/4.2.1-200522-master/share/gridlabd/csv-config2glm-config.py", line 9, in convert
    for row in reader:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
ERROR    [INIT] : GldMain::subcommand(format='/usr/local/bin/python3 %s -i %s -o %s %s',...): command '/usr/local/bin/python3 /usr/local/opt/gridlabd/4.2.1-200522-master/share/gridlabd/csv2glm.py -i config528.csv -o config528.glm -f config -t config' returns code 1
ERROR    [INIT] : /usr/local/opt/gridlabd/4.2.1-200522-master/share/gridlabd/csv2glm.py: return code 1

~~~

## Expected behavior
It should convert the file and load it.

## System information
* GridLAB-D version: HiPAS GridLAB-D 4.2.1-200522 (master) Linux
* Operating system: Linux e578f61b24c5 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dchassin** [comment]
The encoding used is obviously not supported. CSV files should always be saved in compatible encodings, e.g., `utf-8`.
