### ISSUE TITLE
"expected time value" error when using single quotes and ISO8601 datetime

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#712]
## Problem description
When using ISO8601 datetimes for starttime and stoptime with single quotes, the simulation errors out with "expected time value" error.  Single quotes without ISO8601 works and ISO8601 with double quotes works

## Steps to reproduce
1. Download the attached GLM file
2. Run GLM file

## Expected behavior
Simulation succeeds successfully

## System information

    GridLAB-D version: GridLAB-D 4.2.0-191022 (master) LINUX
    Operating system: (Docker Container): Linux 35905cd1ca48 5.4.11-050411-generic #202001120738 SMP Sun Jan 12 12:40:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Attachments
GLM file attached.
[test.zip](https://github.com/slacgismo/gridlabd/files/4894684/test.zip)

**Comment by dchassin** [comment]
Single quotes are no longer supported.  Please use double quotes for all values containing valid delimiters.
