### ISSUE TITLE
Add requests library to python environment in GridLAB-D docker image

### ISSUE THREAD

**Issue by yeyanzhu** [arras-energy/gridlabd-old#730]
## Background
When certain python programs run within GridLAB-D docker container in order to make HTTP requests (e.g. REST API call) to external parties, the python _requests_ library is needed to support these functions.

## Proposed solution
The python environment within GridLAB-D docker image has _requests_ library pre-installed.

**Comment by dchassin** [comment]
@yeyanzhu, is this still unresolved?  If so, which version of requests is needed?

**Comment by yeyanzhu** [comment]
We find a way to solve this issue, not using the request library directly.
