### ISSUE TITLE
Ability to export a complex multi-GLM model into a single GLM model

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#74]
It should be possible to export a multi-GLM model into a single GLM model.  There should be the option either include or not include macros/includes in the simple file.

**Comment by ryanmmmmm** [comment]
the exported GLM should be a "data only" glm basically, meaning no variables using {}, includes, macros,

**Comment by aivanova5** [comment]
@dchassin We need to add functionality for module.class (ex tape vs mysql recorder )

**Comment by dchassin** [comment]
Include examples of usage with https://github.com/dchassin/gridlabd/wiki/glm_save_options.

**Comment by dchassin** [comment]
@aivanova5, please close if current capability is acceptable.
