### ISSUE TITLE
Library command doesn't give access to contents of the uploaded file within GLM script

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#754]
## Problem description

~~~
#library get "wood_pole.glm"
~~~
When used within GLM script the file itself doesn't get uploaded - therefore can't use the the objects inside. 

## Steps to reproduce

(Explain how to reproduce the behavior, e.g.,)
1. Run "test_pole.glm" as amended above.
[test_pole.glm.zip](https://github.com/slacgismo/gridlabd/files/5273014/test_pole.glm.zip)

## Expected behavior
Expect to be able to refer to configurations defined in wood_pole.glm in the slacgismo/gridlabd-library repo

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.2.11-200923 (develop-add-server-control-stop) Darwin
* Operating system: Darwin pc95555.lan 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

## Supporting information

n/a

## Attachments

See above

**Comment by dchassin** [comment]
The problem is that `#include` does not automatically search the library folder and subdirectories and cannot find the downloaded library file in its subfolder within the shared library folder. We need modify `#include` to use `GLPATH` when finding its file.
