### ISSUE TITLE
Pole model doesn't handle faults with high speed winds 

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#763]
## Problem description
High wind scenario results in the error below:
~~~
pc95555:autotest alyona_slac$ gridlabd test_IEEE_13_pole.glm
WARNING  [2020-07-01 02:00:00 EDT] : regulators are neglected from the fault calculation
ERROR    [2020-07-01 02:00:00 EDT] : sync_pole(obj=41;n633): [powerflow/link.cpp:7717] unable to update objects for reliability effects (function 'reliability_alterations' not defined)
ERROR    [2020-07-01 02:00:00 EDT] : 2020-07-01 02:00:00 EDT: object n633 stopped its clock (exec)!
ERROR    [2020-07-01 02:00:00 EDT] : exec halted: synchronization failed
FATAL    [2020-07-01 02:00:00 EDT] : shutdown after simulation stopped prematurely
FATAL    [2020-07-01 02:00:00 EDT] : environment startup failed: No such file or directory
WARNING  [2020-07-01 02:00:00 EDT] : last warning message was repeated 1 times

~~~

## Steps to reproduce
1. Run glm
[Archive.zip](https://github.com/slacgismo/gridlabd/files/5302099/Archive.zip)

## Expected behavior
Fault in pole triggering a repair rather than error in simulation

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.2.11-200928 (develop-single-file-fix) Darwin
* Operating system: Darwin pc95555.lan 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

## Supporting information
N/A

## Attachments
See above

**Comment by dchassin** [comment]
@aivanova5, can we close this issue now?
