### ISSUE TITLE
Pole Status does not remain in "FAILED" state and Service Status does not remain in "OUT_OF_SERVICE" state

### ISSUE THREAD

**Issue by jcald1** [arras-energy/gridlabd-old#78]
When the pole stress reaches 1 but then later in the simulation it falls below 1, the pole status goes back to "OK" and the service status goes back to "IN_SERVICE".

This can be replicated in the GRIP ieee123 pole model:

start time 01-31-03 19:00
stop time 01-31-03 21:52
node:  node_13

**Comment by dchassin** [comment]
This is a result of the `repair_time` parameter.  To prevent the pole from being repaired, use `repair_time TS_NEVER`.

**Comment by dchassin** [comment]
Adding this to PR #63.
