### ISSUE TITLE
Converter for pole objects

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#795]
## Background
To stream line the resilience analysis it is necessary to have a converter that can create or replace nodes with pole objects based on properties defined in a csv / json file allowing the user to upload and quickly determine the vulnerability without having to define the poles themselves in glm format. 

(1) It can be unnecessary to analyze the pole vulnerabilities with a distribution network. Certain use-cases lack the need to model the entire system and may only require a coarse pole vulnerability analysis to pin-point areas of focus. For the first pass of the converter, the focus should be on creating a standalone file that can run pole analysis on the specifications in the CSV/JSON file and disregard the network entirely. 

(2) Enhance the pole converter with the ability to replace nodes in a system model with pole objects. I.e. populate the model with poles instead of nodes while correlating latitude and longitude. 

## Proposed solution
Write a python script that handles the above conversions from a csv file or json file (likely generated by SPIDACalc software or alike). Follow the format of other converters through definition of a new type for conversion. 

## Alternatives
n/a

## Additional context
Relevant for the GRIP project deployment.

**Comment by dchassin** [comment]
The revised method of modeling poles are children of nodes separately should address this. @aivanova5, pls confirm and close if issues is resolved.
