### ISSUE TITLE
Slack node recorder records real instead of reactive power

### ISSUE THREAD

**Issue by mlamlamla** [arras-energy/gridlabd-old#799]
## Problem description

When recording reactivating

## Steps to reproduce

1. Include recorder:

object meter {
	name node_149;
	nominal_voltage 24.941kV;
	phases ABCN;
	bustype SWING;
	object recorder 
		property measured_real_power, measured_reactive_power; 
		file load_node_149.csv;
		interval 1min;
	};
}

2. Compare  measured_real_power  and measured_reactive_power csv print out

## Expected behavior

measured_real_power  and measured_reactive_power should at least be two different numbers. Instead, they are identical (tested for one month, so it's probably not by chance).

## System information

REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
slacgismo/gridlabd               latest              0a08f9ff2f7c        13 days ago         2.14GB
(latest docker image from end of October)

**Comment by dchassin** [comment]
This behavior is due to the model structure and is not a problem with the solver.
