### ISSUE TITLE
Recorder print out correction

### ISSUE THREAD

**Issue by mlamlamla** [arras-energy/gridlabd-old#800]
## Background

The recorder print out for different objects differs in format. For a node recorder, for instance, the print out runs to the end date minus the simulation interval (e.g.for an end date of 08/01/16 00:00, the last recorded data point is 07/31/16 23:59) and terminated with the statement '# end of tape'. For the house recorder (property total_load), the print out runs to the end of the simulation (e.g.for an end date of 08/01/16 00:00, the last recorded data point is 08/01/16 00:00) and does not print a terminating statement. 

## Proposed solution

All recorders should run until the end date and NOT have a terminating statement as it causes trouble with data reading methods such as pandas.read_csv().

## Additional context

Reproduction:

1. Include recorders

object group_recorder {
	name rec_total_load;
	group "class=house";
	property total_load;
	file total_load_all.csv;
	interval 60;
}

object group_recorder {
	name rec_total_load;
	group "class=house";
	property total_load;
	file total_load_all.csv;
	interval 60;
}

2. Compare print outs

**Comment by dchassin** [comment]
This should be addressed by using the comment option when read CSV in pandas.
