### ISSUE TITLE
Object upgrade capability through python

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#852]
## Background
For the resilience use-case template standards there needs to be a way to upgrade an object from... for example... node to pole at either on_create or on_init which will allow to link pole data to any node on the network.

## Proposed solution
??

## Alternatives
n/a

## Additional context
n/a

**Comment by dchassin** [comment]
This is basically impossible using the current implementation of the core. The only solution is to specify the parent of the pole as the node and let the solver merge them.
