### ISSUE TITLE
Template environment is not set correctly

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#855]
## Problem description

When using Mac OS X build, templates are not accessible.

## Steps to reproduce

(Explain how to reproduce the behavior, e.g.,)
1. `gridlabd template get ica`
2. `gridlabd ica_analysis.glm`
3. Exhibit no errors.

## Expected behavior

Access templates without specifying path through /usr/local/share/gridlabd/template/...

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.2.18-210303 (develop-fix-progress-flush) Darwin
* Operating system: Darwin PC95555.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

## Supporting information

n/a

## Attachments

pc95555:oct262020 alyona_slac$ gridlabd --verbose ica_analysis.glm
   ... file '/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/share/gridlabd/gridlabd.conf' is 1502 bytes long
   ... include_file(char *incname='mingw.conf', char *buffer=0x0x7ffeea46808e, int size=16370): search of GLPATH='/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/lib/gridlabd:/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/share/gridlabd:/usr/local/share/gridlabd/template/ica_analysis' result is '/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/share/gridlabd/mingw.conf'
   ... mingw.conf(30): included file is 624 bytes long
   ... include_file(char *incname='gnuplot.conf', char *buffer=0x0x7ffeea468090, int size=16368): search of GLPATH='/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/lib/gridlabd:/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/share/gridlabd:/usr/local/share/gridlabd/template/ica_analysis' result is '/usr/local/opt/gridlabd/4.2.18-210303-develop-fix-progress-flush/share/gridlabd/gnuplot.conf'
   ... gnuplot.conf(34): included file is 278 bytes long
   ... 0 object loaded
ERROR    [INIT] : unable to load 'ica_analysis.glm': No such file or directory
   ... model TRL is UNKNOWN
FATAL    [INIT] : shutdown after command line rejected
   ... load time: 0 sec
   ... starting up batch environment
   ... initializing objects...
   ... creating index 0
   ... creating index 1
   ... creating index 2
   ... shuffled -10 lists in index 0
   ... shuffled -10 lists in index 1
   ... shuffled -10 lists in index 2
   ... shutdown complete
   ... elapsed runtime 0 seconds
   ... exit code 5
   ... elapsed runtime 0 seconds
   ... exit code 5

**Comment by dchassin** [comment]
Would it make sense to use a command line argument to identify the next parameter as a template so it loads it from the correct folder?  E.g.,
~~~
gridlabd my_model.glm -t ica_analysis
~~~
