### ISSUE TITLE
Templates download into two folders

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#857]
## Problem description

Template get results in templates ending up in two folders: 

~~~
PC95555:SLAC_GIS_API alyona_slac$ ls $(gridlabd --version=install)/share/gridlabd/template
US		ica_analysis
PC95555:SLAC_GIS_API alyona_slac$ ls $(gridlabd --version=install)/share/gridlabd/template/ica_analysis
ica_analysis.glm	ica_analysis.md		ica_analysis.py
PC95555:SLAC_GIS_API alyona_slac$ ls $(gridlabd --version=install)/share/gridlabd/template/ica_analysis/US/CA/SLAC
ls: /usr/local/opt/gridlabd/4.2.18-210312-develop-add-template-cmdarg/share/gridlabd/template/ica_analysis/US/CA/SLAC: No such file or directory
PC95555:SLAC_GIS_API alyona_slac$ ls $(gridlabd --version=install)/share/gridlabd/template/US/CA/SLAC/ica_analysis
__pycache__		ica_analysis.glm	ica_analysis.md		ica_analysis.py
~~~

## Steps to reproduce

See above

## Expected behavior

One place for template download

## System information

* GridLAB-D version:HiPAS GridLAB-D 4.2.18-210312 (develop-add-template-cmdarg) Darwin
* Operating system: Darwin PC95555.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

## Supporting information
n/a

## Attachments

n/a

**Comment by dchassin** [comment]
This appears to be fixed.
