### ISSUE TITLE
Not all glyphs are displayed in folium HTML map viewer converter

### ISSUE THREAD

**Issue by avpeery** [arras-energy/gridlabd-old#900]
## Problem description

When displaying folium HTML map view - some glyphs (glyphs for poles) do not show.  The problems differ depending on which --glyphs=<choice> you select. Valid choices are fa and glyphicons.

## Steps to reproduce

N/A

## Expected behavior

Excepted to see cross glyph where there are poles on map viewer.

**Comment by avpeery** [comment]
Icons from v5 release of fontawesome are not supported by Folium (icon "cross" is a part of v5 release). See: https://stackoverflow.com/questions/58607693/how-to-use-folium-icon-with-fontawesome

**Comment by avpeery** [comment]
For glyphicons, https://bootstrapdocs.com/v3.2.0/docs/components/ are the only available options (3.2)

**Comment by dchassin** [comment]
What are the chances we could modify folium so we could make our own icons?

**Comment by avpeery** [comment]
It is possible to fork folium to modify it to allow for v5 fontawesome icons. I think it's also possible to do custom icons with a src url. This source is possibly dated though from 2015 on custom icons: https://ocefpaf.github.io/python4oceanographers/blog/2015/11/02/icons/
