### ISSUE TITLE
Cyme conversion result in mysterious error

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#978]
## Problem description

Cyme converter produces the error `config.glm(1): @ syntax error`.

## Steps to reproduce

1. The working branch is `develop-add-cyme-converter` for GridLAB-D, and `develop` for openfido/cli.
2. The test command is: `gridlabd -D mdb_load_options="-t cyme -p branch=develop" IEEE13.mdb`

## System information

* GridLAB-D version: `4.2.26-210812-develop_add_cyme_converter`
* System version: `Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

## Attachments
Attached please find the zip file for the test case which includes the .mdb dataset and configuration csv files.
[input_1.zip](https://github.com/slacgismo/gridlabd/files/6995778/input_1.zip)

**Comment by dchassin** [comment]
@xiefuhong, which gridlabd version are you using?

**Comment by xiefuhong** [comment]
> @xiefuhong, which gridlabd version are you using?

My working branch is `develop-add-cyme-converter`.
